# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160302_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meetup_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
