# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160304_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='meetup_link',
            new_name='event_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
