# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_meetup_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meetup_id',
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='group_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
