# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
